name: Bug Report
description: Create a report to help us improve the Modpack.
title: "[BUG] "
labels: [bug]
body:
  - type: dropdown
    id: type
    attributes:
      label: Is this a client or server issue?
      description: Please select one option
      options:
        - Client
        - Server
    validations:
      required: true
  - type: input
    id: modpack-version
    attributes:
      label: Modpack Version
      description: Enter the modpack version you are using.
      placeholder: e.g. 0.1.6
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: A clear and concise list of steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context about the problem here (Screenshots, User Modifications).
