name: Pull Request Form
description: A simple form for pull requests
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of your changes
      placeholder: What did you change and why?
    validations:
      required: true
  - type: user
    id: assignee
    attributes:
      label: Assignee
      description: Please assign @FooterMan15 to review your pull request
    validations:
      required: true
      allowed-login: FooterMan15
